language: scala

sudo: required

services:
  - docker

jdk:
  - oraclejdk8
scala:
  - 2.11.8
#  - 2.12.1
  
after_success:
  - sbt docker:publishLocal
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push scaficobalt/executionservice;
    docker push scaficobalt/ingestionservice;
    docker push scaficobalt/domainservice;
    docker push scaficobalt/sensorservice;
    docker push scaficobalt/visualizerservice;
    fi
