language: scala

sudo: required

services:
  - docker

jdk:
  - oraclejdk8
scala:
  - 2.11.8
  - 2.12.1

script:
  - sbt docker:publishLocal
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push executionservice:latest;
    docker push ingestionservice:latest;
    docker push domainservice:latest;
    docker push sensorservice:latest;
    docker push visualizerservice:latest;
    fi
