version: "3"

services:

  domainDb:
    image: redis
    ports:
      - "6379"
    networks:
      domainnet:
        aliases:
          - redis

  executionDb:
    image: redis
    ports:
      - "6379"
    networks:
      executionnet:
        aliases:
          - redis

  sensorDb:
    image: redis
    ports:
      - "6379"
    networks:
      sensornet:
        aliases:
          - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "127.0.0.1:15672:15672"
    networks:
      - network

networks:
  network:
  domainnet:
  sensornet:
  executionnet:
