version: "3"

services:

  ingestionService:
    image: ingestionservice:0.1.0
    ports:
      - "127.0.0.1:80:8080"
    networks:
      - sensornet
      - network

  domainService:
    image: domainservice:0.1.0
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - ingestionService
    networks:
      network:
        aliases:
          - domain
      domainnet:

  executionService:
    image: executionservice:0.1.0
    ports:
      - "127.0.0.1:8083:8080"
    depends_on:
          - ingestionService
    networks:
      - network
      - executionnet

  sensorService:
    image: sensorservice:0.1.0
    ports:
      - "8082:8080"
    networks:
      sensornet:
      network:
        aliases:
          - sensor

networks:
  network:
  domainnet:
  sensornet:
  executionnet: