version: "3"

services:

  domainDb:
    image: redis
    ports:
      - "6379"
    networks:
      domainnet:
        aliases:
          - redis

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - network
    volumes:
      - /Users/Thomas/IdeaProjects/scafi-cobalt/docker/prometheus.yml:/etc/prometheus/prometheus.yml

  executionDb:
    image: redis
    ports:
      - "6379"
    networks:
      executionnet:
        aliases:
          - redis

  sensorDb:
    image: redis
    ports:
      - "6379"
    networks:
      sensornet:
        aliases:
          - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network

networks:
  network:
  domainnet:
  sensornet:
  executionnet:
