version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  consul:
    image: consul:latest
    ports:
      - "8500:8500"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - consul
    volumes:
      - /Users/Thomas/IdeaProjects/scafi-cobalt/docker/prometheus.yml:/etc/prometheus/prometheus.yml

  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    depends_on:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  ingestiondb:
    image: redis
    ports:
      - "6379"
  executiondb:
    image: redis
    ports:
      - "6379"
  domaindb:
    image: redis
    ports:
      - "6379"