global:
  scrape_interval: 5s


  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'scafi_cobalt-monitor'

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'scafi_cobalt'

    consul_sd_configs:
      - server: 'consul:8500'

#    static_configs:
#      - targets: ['domain:8080']
#      - targets: ['execution:8080']
#      - targets: ['ingestion:8080']
