version: "3"

services:

  ingestion:
    image: scaficobalt/ingestionservice:latest
    deploy:
      replicas: 1

  domain:
    image: scaficobalt/domainservice:latest
    depends_on:
      - ingestion
    deploy:
      replicas: 1

  execution:
    image: scaficobalt/executionservice:latest
    depends_on:
      - ingestion
    deploy:
      replicas: 1

  sensor:
    image: scaficobalt/sensorservice:latest

  visualizerService:
    image: scaficobalt/visualizerservice:latest
    ports:
      - "8000:8000"
      - "8001:8001"
    deploy:
      replicas: 1
