version: "3"

services:

  ingestionService:
    image: scaficobalt/ingestionservice:latest
    ports:
      - "80:8080"
    networks:
      sensornet:
      network:
        aliases:
          - ingestion
    deploy:
      replicas: 1

  domainService:
    image: scaficobalt/domainservice:latest
    ports:
      - "8081:8080"
    depends_on:
      - ingestionService
    networks:
      network:
        aliases:
          - domain
      domainnet:
    deploy:
      replicas: 3

  executionService:
    image: scaficobalt/executionservice:latest
    ports:
      - "8083:8080"
    depends_on:
      - ingestionService
    networks:
      network:
        aliases:
          - execution
      executionnet:
    deploy:
      replicas: 1

  sensorService:
    image: scaficobalt/sensorservice:latest
    ports:
      - "8082:8080"
    networks:
      sensornet:
      network:
        aliases:
          - sensor

networks:
  network:
  domainnet:
  sensornet:
  executionnet: