version: "3"

services:

  ingestionService:
    image: scaficobalt/ingestionservice
    ports:
      - "127.0.0.1:80:8080"
    networks:
      - sensornet
      - network
    deploy:
      replicas: 2

  domainService:
    image: scaficobalt/domainservice
    ports:
      - "127.0.0.1:8081:8080"k
    depends_on:
      - ingestionService
    networks:
      network:
        aliases:
          - domain
      domainnet:
#    deploy:
#      replicas: 3

  executionService:
    image: scaficobalt/executionservice
    ports:
      - "127.0.0.1:8083:8080"
    depends_on:
      - ingestionService
    networks:
      - network
      - executionnet
    deploy:
      replicas: 10

  sensorService:
    image: scaficobalt/sensorservice
    ports:
      - "8082:8080"
    networks:
      sensornet:
      network:
        aliases:
          - sensor

networks:
  network:
  domainnet:
  sensornet:
  executionnet: