version: "3"

services:

  ingestion:
    image: scaficobalt/ingestionservice:latest
    ports:
      - "80:8080"
    deploy:
      replicas: 2

  domain:
    image: scaficobalt/domainservice:latest
    depends_on:
      - ingestion
    deploy:
      replicas: 5

  execution:
    image: scaficobalt/executionservice:latest
    depends_on:
      - ingestion
    deploy:
      replicas: 5

  sensor:
    image: scaficobalt/sensorservice:latest
    deploy:
      replicas: 2

  visualizerService:
    image: scaficobalt/visualizerservice:latest
    ports:
      - "8000:8000"
      - "8001:8001"
    deploy:
      replicas: 1
