version: "3"

services:

  ingestionService:
    image: scaficobalt/ingestionservice:latest
    ports:
      - "8080"
      - "80:8080"
    networks:
      sensornet:
      network:
        aliases:
          - ingestion
    deploy:
      replicas: 3

  visualizerService:
      image: scaficobalt/visualizerservice:latest
      ports:
        - "8000"
        - "8001"
        - "8000:8000"
        - "8001:8001"
      networks:
        network:
          aliases:
            - visualizer
      deploy:
        replicas: 1

  domainService:
    image: scaficobalt/domainservice:latest
    ports:
      - "8080"
      - "8081:8080"
    depends_on:
      - ingestionService
    networks:
      network:
        aliases:
          - domain
          - domainService
      domainnet:
    deploy:
      replicas: 3

  executionService:
    image: scaficobalt/executionservice:latest
    ports:
      - "8080"
      - "8083:8080"
    depends_on:
      - ingestionService
    networks:
      network:
        aliases:
          - execution
          - executionService
      executionnet:
    deploy:
      replicas: 1

  sensorService:
    image: scaficobalt/sensorservice:latest
    ports:
      - "8080"
      - "8082:8080"
    networks:
      sensornet:
      network:
        aliases:
          - sensor

networks:
  network:
    driver:
      "overlay"
  domainnet:
  sensornet:
  executionnet: